# Generated by Django 5.1.2 on 2024-10-20 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField()),
                ('farewell_message', models.TextField()),
                ('inactivity_timeout', models.IntegerField(default=600)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='chatbot_images/')),
                ('chat_icon', models.ImageField(blank=True, null=True, upload_to='chatbot_images/')),
            ],
            options={
                'verbose_name': 'Paramètres du Chatbot',
                'verbose_name_plural': 'Paramètres du Chatbot',
            },
        ),
        migrations.CreateModel(
            name='FAQFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], max_length=2)),
                ('file', models.FileField(upload_to='faq_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('language',)},
            },
        ),
    ]
